# This is a basic workflow to test Bisulfite is working

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Install dependencies
      run: |
        sudo apt install bowtie2
        sudo apt-get install libgd-perl
        sudo cpan App::cpanminus
        sudo cpanm GD::Graph
        
        sudo apt install bismark
             
    # Download and extract useful files
    - name: Download files
      run: |
        # wget https://www.bioinformatics.babraham.ac.uk/projects/bismark/test_data.fastq
        # wget https://github.coqqm/FelixKrueger/Bismark/archive/0.22.3.tar.gz
        # tar xvzf 0.22.3.tar.gz
        bismark -h
        
        
        
        # $GITHUB_WORKSPACE/fastq_screen --get_genomes --bisulfite
        
    # Run FastQ Screen
    - name: Run FastQ Screen
      run: |
        $GITHUB_WORKSPACE/fastq_screen --conf ./FastQ_Screen_Genomes/fastq_screen.conf *.fastq.gz
